### ISSUE TITLE
Redirect to youtube-nocookie by default or depending of a setting

### ISSUE THREAD

**Issue by brunob** [rhnvrm/yt2embed#1]
Hi and thanks for this addon, what do you think of redirect by default to youtube-nocookie embeds which are better for privacy ?

**Comment by rhnvrm** [comment]
Hey

If I recall correctly, I had tried this while developing the extension but had forgotten why I had gone ahead with a simple youtube redirect.

Just checked this again now;

![Screenshot_2021-11-17_00-25-44](https://user-images.githubusercontent.com/952036/142048297-a968f812-5c24-434f-9eff-860cb20defdb.png)


Seems like it was some HSTS issue. If you find some alternate solution, do let me know.

**Comment by brunob** [comment]
Thx for the quick answer, i've tested the patch and from my side it works well with FF 94.0

```javascript
function yt_redirector(requestDetails)
{
  var u = new URL(requestDetails.url)
  var v = u.searchParams.get("v")
  if (v === "") {
    return {};
  }
  return {
    redirectUrl: "https://www.youtube-nocookie.com/embed/" + v
  };
}

browser.webRequest.onBeforeRequest.addListener(
  yt_redirector,
  {
    urls: [
      '*://www.youtube.com/watch*',
      '*://youtube.com/watch*'
    ]
  },
  ["blocking"]
);
```

Test url is https://www.youtube.com/watch?v=EguHmYWXpZ4

**Comment by rhnvrm** [comment]
Hmm... I have pushed the patch. Although intermittently it keeps showing the HSTS warning for me. I guess it could be some issue at my end. I'll update the plugin on moz soon.

Thanks for your suggestion and help!

**Comment by rhnvrm** [comment]
@brunob https://addons.mozilla.org/en-US/firefox/addon/yt2embed/ is now updated to v0.0.2

**Comment by brunob** [comment]
(y) i'll test it asap and tell you if it works well :)
